# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 02:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='mensagem',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='telefone',
        ),
        migrations.AddField(
            model_name='consulta',
            name='email',
            field=models.CharField(default=datetime.datetime(2016, 1, 29, 2, 8, 6, 237844, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='nome',
            field=models.CharField(default=datetime.datetime(2016, 1, 29, 2, 8, 10, 862082, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
