# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20160129_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='enviado',
            field=models.BooleanField(default=False),
        ),
    ]
